import AccessRestricted from "@/pages/AccessRestricted";
import { NewProjectDialog } from "@/components/fix/NewProjectDialog";
import { StatusBadge } from "@/components/fix/StatusBadge";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { formatCurrency, formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowUpRight, CheckCircle2, CircleAlert, DollarSign, Radar, Sparkles } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLocation } from "wouter";

function Metric({ icon: Icon, label, value, detail, tone = "dark" }: { icon: typeof Activity; label: string; value: string | number; detail: string; tone?: "dark" | "lime" | "soft" }) {
  const className = tone === "lime" ? "bg-[#c7f35b] text-[#122014]" : tone === "soft" ? "bg-[#e6efe8] text-[#203328]" : "bg-[#1c2d23] text-white";
  return <Card className="overflow-hidden border-[#dfe7e1] shadow-[0_10px_30px_rgba(19,42,28,.04)]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-[#708075]">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-[#1d2d23]">{value}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${className}`}><Icon className="h-4 w-4" /></div></div><p className="mt-5 text-xs text-[#85948b]">{detail}</p></CardContent></Card>;
}

export default function Home() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const dashboard = trpc.fix.dashboard.useQuery(undefined, { enabled: user?.role === "owner" || user?.role === "admin" });
  if (user?.role !== "owner" && user?.role !== "admin") return <AccessRestricted />;
  if (dashboard.isLoading) return <div className="grid gap-5"><Skeleton className="h-28 rounded-3xl" /><div className="grid gap-4 md:grid-cols-4">{Array.from({ length: 4 }).map((_, i) => <Skeleton className="h-40 rounded-2xl" key={i} />)}</div></div>;
  if (dashboard.error) return <div className="rounded-2xl border border-red-100 bg-red-50 p-5 text-sm text-red-700">Unable to load the control center: {dashboard.error.message}</div>;
  const data = dashboard.data!;
  return <div className="space-y-7"><section className="relative overflow-hidden rounded-3xl bg-[#193023] px-6 py-7 text-white shadow-[0_20px_55px_rgba(24,48,34,.18)] lg:px-8"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-[#c7f35b]/10 blur-2xl" /><div className="relative flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-4 flex items-center gap-2 text-xs font-medium text-[#c7f35b]"><Sparkles className="h-3.5 w-3.5" /> PRIVATE GIC CONTROL PLANE</div><h1 className="max-w-xl text-2xl font-semibold tracking-tight sm:text-3xl">Operate every client engagement with evidence, oversight and a complete decision trail.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#aabbb0]">The pipeline is quiet until you register a real opportunity. GIC preserves project state, approval decisions and agent activity from the first triage through delivery.</p></div><NewProjectDialog /></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Radar} label="Active projects" value={data.metrics.activeProjects} detail={`${data.metrics.pendingApprovals} approval${data.metrics.pendingApprovals === 1 ? "" : "s"} awaiting review`} tone="dark" /><Metric icon={DollarSign} label="Recognized revenue" value={formatCurrency(data.metrics.revenueCents)} detail="Delivered projects only" tone="lime" /><Metric icon={Sparkles} label="Average match score" value={`${data.metrics.averageMatchScore}%`} detail="Across scored opportunities" tone="soft" /><Metric icon={CheckCircle2} label="Completion rate" value={`${data.metrics.completionRate}%`} detail={`${data.metrics.completedProjects} delivered project${data.metrics.completedProjects === 1 ? "" : "s"}`} tone="dark" /></section>
    <section className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card className="border-[#dfe7e1]"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-[#e7ede8] px-5 py-4"><div><h2 className="text-sm font-semibold text-[#203128]">Live project pipeline</h2><p className="mt-1 text-xs text-[#758479]">Persistent state and last activity for current engagements</p></div><button onClick={() => setLocation("/pipeline")} className="text-xs font-semibold text-[#2a693e] hover:underline">View pipeline</button></div>{data.projects.length === 0 ? <div className="grid min-h-52 place-items-center p-6 text-center"><div><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-[#eef4ef] text-[#62816b]"><Radar className="h-5 w-5" /></div><p className="mt-3 text-sm font-medium text-[#34473a]">No opportunities registered</p><p className="mt-1 text-xs text-[#829087]">Start with a real client opportunity to activate the lifecycle.</p></div></div> : <div>{data.projects.map(project => <button onClick={() => setLocation(`/projects/${project.publicId}`)} key={project.publicId} className="flex w-full items-center gap-4 border-b border-[#edf1ee] px-5 py-4 text-left transition hover:bg-[#f7faf7] last:border-0"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#edf4ed] text-xs font-bold text-[#2f6d43]">{project.title.slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[#25372b]">{project.title}</p><p className="mt-1 text-xs text-[#829087]">Updated {formatDate(project.updatedAt)}</p></div><div className="hidden text-right sm:block"><p className="text-xs font-medium text-[#536258]">{formatCurrency(project.budgetCents, project.currency)}</p><p className="mt-1 text-[10px] text-[#829087]">{project.completionPercent}% complete</p></div><StatusBadge status={project.status} /><ArrowUpRight className="h-4 w-4 text-[#98a69d]" /></button>)}</div>}</CardContent></Card>
      <Card className="border-[#dfe7e1]"><CardContent className="p-0"><div className="border-b border-[#e7ede8] px-5 py-4"><h2 className="text-sm font-semibold text-[#203128]">Decision queue</h2><p className="mt-1 text-xs text-[#758479]">Human review is mandatory for sensitive actions</p></div>{data.pendingApprovals.length === 0 ? <div className="grid min-h-52 place-items-center p-6 text-center"><div><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-[#eef4ef] text-[#62816b]"><CheckCircle2 className="h-5 w-5" /></div><p className="mt-3 text-sm font-medium text-[#34473a]">Approval inbox is clear</p><p className="mt-1 text-xs text-[#829087]">No agent can take an irreversible action without you.</p></div></div> : <div>{data.pendingApprovals.slice(0, 4).map(item => <button onClick={() => setLocation("/approvals")} className="w-full border-b border-[#edf1ee] px-5 py-4 text-left transition hover:bg-[#f7faf7] last:border-0" key={item.publicId}><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-semibold text-[#33473a]">{item.title}</p><CircleAlert className={`h-4 w-4 shrink-0 ${item.gateType === "high_risk_escalation" ? "text-red-500" : "text-amber-500"}`} /></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#758479]">{item.summary}</p><p className="mt-2 text-[10px] font-medium uppercase tracking-wide text-[#84948a]">{item.project.title}</p></button>)}</div>}</CardContent></Card></section>
    <section className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card className="border-[#dfe7e1]"><CardContent className="p-0"><div className="border-b border-[#e7ede8] px-5 py-4"><h2 className="text-sm font-semibold text-[#203128]">Agent activity</h2><p className="mt-1 text-xs text-[#758479]">Latest structured runs across the agency</p></div>{data.recentRuns.length === 0 ? <p className="p-5 text-sm text-[#849188]">No agent run has been started for a real project.</p> : data.recentRuns.map(run => <div key={run.publicId} className="flex items-center gap-3 border-b border-[#edf1ee] px-5 py-3.5 last:border-0"><div className="h-2 w-2 rounded-full bg-[#7fb945]" /><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-[#33473a]">{run.role}</p><p className="mt-1 truncate text-xs text-[#7b8a80]">{run.outputSummary || run.inputSummary}</p></div><span className="text-[10px] text-[#85948a]">{formatDate(run.createdAt)}</span></div>)}</CardContent></Card>
      <Card className="border-[#dfe7e1]"><CardContent className="p-0"><div className="border-b border-[#e7ede8] px-5 py-4"><h2 className="text-sm font-semibold text-[#203128]">System timeline</h2><p className="mt-1 text-xs text-[#758479]">Evidence-led record of decisions and state changes</p></div>{data.recentEvents.length === 0 ? <p className="p-5 text-sm text-[#849188]">Events will appear after the first project is registered.</p> : data.recentEvents.slice(0, 5).map(event => <div key={event.publicId} className="border-b border-[#edf1ee] px-5 py-3.5 last:border-0"><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-semibold text-[#33473a]">{event.title}</p><span className="text-[10px] text-[#85948a]">{formatDate(event.createdAt)}</span></div><p className="mt-1 line-clamp-1 text-xs text-[#7b8a80]">{event.detail}</p></div>)}</CardContent></Card></section>
  </div>;
}
