import AccessRestricted from "@/pages/AccessRestricted";
import { ApprovalActions } from "@/components/fix/ApprovalActions";
import { WebActionExecutionControls } from "@/components/fix/WebActionExecutionControls";
import { StatusBadge } from "@/components/fix/StatusBadge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { formatCurrency, formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Activity, Bot, Download, FileCheck2, FlaskConical, Globe2, Play, RefreshCw, ShieldCheck, TerminalSquare } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { useRoute } from "wouter";

const agentRoles = ["Lead Architect", "Manager", "Scout", "Proposal", "Backend Team", "AI/Automation Team", "QA/Security Agent", "Delivery Manager"] as const;

function downloadMarkdown(filename: string, content: string) {
  const anchor = document.createElement("a");
  anchor.href = URL.createObjectURL(new Blob([content], { type: "text/markdown;charset=utf-8" }));
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(anchor.href);
}

export default function ProjectDetail() {
  const { user } = useAuth();
  const [, params] = useRoute("/projects/:publicId");
  const projectPublicId = params?.publicId ?? "";
  const utils = trpc.useUtils();
  const detail = trpc.fix.projects.detail.useQuery({ projectPublicId }, { enabled: Boolean(projectPublicId) && (user?.role === "owner" || user?.role === "admin") });
  const [selectedRole, setSelectedRole] = useState<(typeof agentRoles)[number]>("Manager");
  const refresh = () => utils.fix.projects.detail.invalidate({ projectPublicId });
  const transition = trpc.fix.projects.transition.useMutation({ onSuccess: () => { refresh(); toast.success("Lifecycle transition checkpointed."); }, onError: e => toast.error(e.message) });
  const request = trpc.fix.approvals.request.useMutation({ onSuccess: () => { refresh(); utils.fix.approvals.listPending.invalidate(); toast.success("Approval gate created."); }, onError: e => toast.error(e.message) });
  const runAgent = trpc.fix.agents.run.useMutation({ onSuccess: () => { refresh(); toast.success("Agent run completed and recorded."); }, onError: e => toast.error(e.message) });
  const runPlanning = trpc.fix.agents.runPlanningHierarchy.useMutation({ onSuccess: () => { refresh(); toast.success("Hierarchical planning pass completed."); }, onError: e => toast.error(e.message) });
  const runWorkstreams = trpc.fix.agents.runSpecialistWorkstreams.useMutation({ onSuccess: data => { refresh(); toast.success(`${data.completedTaskCount} specialist workstream(s) completed.`); }, onError: e => toast.error(e.message) });
  const runQualityGate = trpc.fix.agents.runQualityGate.useMutation({ onSuccess: data => { refresh(); toast.success(data.message); }, onError: e => toast.error(e.message) });
  const runSimulatedTest = trpc.workspace.invokeSimulated.useMutation({ onSuccess: () => { refresh(); toast.success("Simulated workspace test request audited."); }, onError: e => toast.error(e.message) });
  const resume = trpc.fix.projects.resume.useMutation({ onSuccess: () => { refresh(); toast.success("Project resumed from its latest checkpoint."); }, onError: e => toast.error(e.message) });
  const report = trpc.fix.projects.generateReport.useMutation({ onSuccess: data => { downloadMarkdown(`fix-${projectPublicId}-report.md`, data.content); refresh(); toast.success("Operational report exported."); }, onError: e => toast.error(e.message) });
  if (user?.role !== "owner" && user?.role !== "admin") return <AccessRestricted />;
  if (detail.isLoading) return <p className="text-sm text-[#708075]">Loading project record…</p>;
  if (detail.error || !detail.data) return <div className="rounded-2xl border border-red-100 bg-red-50 p-5 text-sm text-red-700">{detail.error?.message || "Project not found."}</div>;
  const data = detail.data; const project = data.project;
  const actionBusy = transition.isPending || request.isPending || runAgent.isPending || runPlanning.isPending || runWorkstreams.isPending || runQualityGate.isPending || resume.isPending;
  const action = (() => {
    if (project.status === "OPPORTUNITY") return <Button disabled={actionBusy} onClick={() => transition.mutate({ projectPublicId, toStatus: "ANALYSIS", reason: "Operator started formal opportunity analysis." })}><Play className="mr-2 h-4 w-4" />Start analysis</Button>;
    if (project.status === "ANALYSIS") return <Button disabled={actionBusy} onClick={() => transition.mutate({ projectPublicId, toStatus: "PROPOSAL_DRAFT", reason: "Analysis is ready for proposal drafting." })}>Open proposal draft</Button>;
    if (project.status === "PROPOSAL_DRAFT") return <Button disabled={actionBusy} onClick={() => request.mutate({ projectPublicId, gateType: "proposal_send", title: "Proposal send review", summary: "A proposal draft is ready for human review. Sending remains disabled until approved.", context: {}, requestedByRole: "Proposal" })}>Request proposal review</Button>;
    if (project.status === "CLIENT_RESPONSE") return <Button disabled={actionBusy} onClick={() => transition.mutate({ projectPublicId, toStatus: "PLANNING", reason: "Client response is ready for project planning." })}>Start project planning</Button>;
    if (project.status === "PLANNING") return <div className="flex flex-wrap gap-2"><Button disabled={actionBusy} onClick={() => runPlanning.mutate({ projectPublicId })}><Bot className="mr-2 h-4 w-4" />Run team planning</Button><Button variant="outline" disabled={actionBusy} onClick={() => transition.mutate({ projectPublicId, toStatus: "EXECUTING", reason: "Operator approved transition from planning to execution." })}>Start execution</Button></div>;
    if (project.status === "EXECUTING") return <div className="flex flex-wrap gap-2"><Button disabled={actionBusy} onClick={() => runWorkstreams.mutate({ projectPublicId })}><Play className="mr-2 h-4 w-4" />Run specialist work</Button><Button variant="outline" disabled={actionBusy} onClick={() => runQualityGate.mutate({ projectPublicId })}><ShieldCheck className="mr-2 h-4 w-4" />Run QA gate</Button></div>;
    if (project.status === "QA_GATE") return <Button disabled={actionBusy} onClick={() => toast.message("QA is in progress. Refresh after the QA/Security Agent completes its structured review.")}>QA in progress</Button>;
    if (["ON_HOLD", "FAILED"].includes(project.status)) return <Button disabled={actionBusy} onClick={() => resume.mutate({ projectPublicId })}><RefreshCw className="mr-2 h-4 w-4" />Resume checkpoint</Button>;
    return null;
  })();
  return <div className="space-y-6"><section className="rounded-3xl border border-[#dce7df] bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={project.status} /><span className="text-xs font-medium uppercase tracking-[0.12em] text-[#88978d]">{project.publicId}</span></div><h1 className="mt-4 text-2xl font-semibold tracking-tight text-[#1e3024]">{project.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#718076]">{project.description}</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[#69796e]"><span>Client: <strong className="text-[#34463a]">{project.clientName || "Not recorded"}</strong></span><span>Budget: <strong className="text-[#34463a]">{formatCurrency(project.budgetCents, project.currency)}</strong></span><span>Match: <strong className="text-[#34463a]">{project.matchScore === null ? "Not scored" : `${project.matchScore}%`}</strong></span><span>Risk: <strong className="capitalize text-[#34463a]">{project.riskLevel}</strong></span></div></div><div className="flex shrink-0 flex-wrap gap-2">{action}<Button variant="outline" onClick={() => report.mutate({ projectPublicId })} disabled={report.isPending}><Download className="mr-2 h-4 w-4" />Export report</Button></div></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.85fr]"><Card className="border-[#dfe7e1]"><CardContent className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-[#26392d]">Hierarchical execution</h2><p className="mt-1 text-xs text-[#7d8c82]">Lead Architect and Manager create bounded work; specialized teams act only within their tasks.</p></div><Badge variant="outline" className="border-[#d9e4dc] text-[#5e7365]">{project.phase}</Badge></div><Separator className="my-5" /><div className="space-y-3">{data.tasks.length === 0 ? <p className="text-sm text-[#819087]">No task has been created yet.</p> : data.tasks.map(task => <div key={task.publicId} className="rounded-xl border border-[#e2ebe4] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-[#2d4033]">{task.title}</p><p className="mt-1 text-xs text-[#7c8d82]">{task.assignedRole} · attempt {task.attemptCount}/{task.maxAttempts}</p></div><Badge variant="outline" className="capitalize">{task.status.replaceAll("_", " ")}</Badge></div><p className="mt-3 text-xs leading-5 text-[#748378]">{task.description}</p>{task.feedback && <p className="mt-3 rounded-lg bg-amber-50 p-2 text-xs text-amber-800">Feedback: {task.feedback}</p>}</div>)}</div></CardContent></Card>
      <Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Agent console</h2><p className="mt-1 text-xs text-[#7d8c82]">Run a scoped structured assessment. LLM output, cost and decision rationale are retained.</p><div className="mt-5 space-y-3"><Select value={selectedRole} onValueChange={value => setSelectedRole(value as (typeof agentRoles)[number])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{agentRoles.map(role => <SelectItem value={role} key={role}>{role}</SelectItem>)}</SelectContent></Select><Button className="w-full" disabled={actionBusy} onClick={() => runAgent.mutate({ projectPublicId, role: selectedRole })}><Bot className="mr-2 h-4 w-4" />Run {selectedRole}</Button><Button variant="outline" className="w-full" disabled={runSimulatedTest.isPending} onClick={() => runSimulatedTest.mutate({ projectPublicId, role: "QA/Security Agent", toolName: "run_tests", payload: { target: "all" } })}><FlaskConical className="mr-2 h-4 w-4" />Audit simulated test request</Button><p className="rounded-lg bg-[#f2f6f3] p-3 text-[11px] leading-5 text-[#718177]"><TerminalSquare className="mr-1 inline h-3.5 w-3.5" />Runner mode: simulated. Requests are validated and audited, but never execute shell commands or modify a file system.</p></div></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-2"><Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Approval history</h2><div className="mt-4 space-y-3">{data.approvals.length === 0 ? <p className="text-sm text-[#819087]">No approval gate has been opened.</p> : data.approvals.map(gate => <div className="rounded-xl border border-[#e2ebe4] p-4" key={gate.publicId}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-[#33463a]">{gate.title}</p><p className="mt-1 text-xs text-[#829087]">{gate.gateType.replaceAll("_", " ")} · {formatDate(gate.createdAt)}</p></div><Badge variant="outline" className="capitalize">{gate.status}</Badge></div><p className="mt-3 text-xs leading-5 text-[#738177]">{gate.summary}</p>{gate.status === "pending" && <div className="mt-4"><ApprovalActions gatePublicId={gate.publicId} onDone={refresh} /></div>}</div>)}</div></CardContent></Card>
      <Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Quality & security</h2><div className="mt-4 space-y-3">{data.qualityRuns.length === 0 ? <p className="text-sm text-[#819087]">Quality evidence appears after QA/Security Agent runs.</p> : data.qualityRuns.map(run => <div className="rounded-xl border border-[#e2ebe4] p-4" key={run.publicId}><div className="flex items-center justify-between"><p className="text-sm font-medium text-[#33463a]">QA run {run.publicId}</p><Badge variant="outline" className="capitalize">{run.status}</Badge></div><p className="mt-2 text-xs text-[#78877e]">Score: {run.score ?? "—"}/100 · retry recommended: {run.retryRecommended ? "yes" : "no"}</p><p className="mt-2 text-xs leading-5 text-[#738177]">{run.summary}</p></div>)}</div></CardContent></Card></section>
    <section><Card className="border-[#dfe7e1]"><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold text-[#26392d]">Web actions</h2><p className="mt-1 text-xs leading-5 text-[#7d8c82]">Site-specific actions are evaluated against the Site Profile allowlist. Public reads use a one-time lease after a separate approval; login, CAPTCHA and external submit remain blocked.</p></div><Badge variant="outline" className="border-[#d9e4dc] text-[#5e7365]">Audited</Badge></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{data.webActions.length === 0 ? <div className="rounded-xl border border-dashed border-[#dbe6de] p-4 text-sm text-[#819087]">No web action is associated with this project. Add an authorized Site Profile before preparing work for an external website.</div> : data.webActions.map(action => <div key={action.publicId} className="rounded-xl border border-[#e2ebe4] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="flex items-center gap-1.5 text-sm font-medium text-[#33463a]"><Globe2 className="h-3.5 w-3.5 text-[#4d825a]" />{action.site.name}</p><p className="mt-1 truncate text-xs text-[#819087]">{action.targetUrl}</p></div><Badge variant="outline" className="capitalize">{action.status.replaceAll("_", " ")}</Badge></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-[#6f8074]"><span>Action: {action.actionType.replaceAll("_", " ")}</span><span>Mode: {action.site.connectionMode}</span><span>{formatDate(action.createdAt)}</span>{action.latestLease && <span>Lease: {action.latestLease.status}</span>}</div><p className="mt-3 rounded-lg bg-[#f3f7f4] p-2.5 text-xs leading-5 text-[#6f8074]">{(action.result as { message?: string; summary?: string } | null)?.summary || (action.result as { message?: string } | null)?.message || "Prepared action metadata retained without external side effects."}</p><div className="mt-3"><WebActionExecutionControls action={action} projectPublicId={projectPublicId} onDone={refresh} /></div></div>)}</div></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Timeline and checkpoints</h2><div className="mt-4 space-y-0">{data.events.length === 0 ? <p className="text-sm text-[#819087]">No events recorded.</p> : data.events.map(event => <div className="relative border-l border-[#dce8df] pb-5 pl-5 last:pb-0" key={event.publicId}><span className="absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full bg-[#80b94b]" /><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-[#33463a]">{event.title}</p><span className="shrink-0 text-[10px] text-[#8a988f]">{formatDate(event.createdAt)}</span></div><p className="mt-1 text-xs leading-5 text-[#78877e]">{event.detail}</p></div>)}</div></CardContent></Card>
      <Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Audit & recovery</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{data.checkpoints.map(checkpoint => <div key={checkpoint.publicId} className="rounded-xl bg-[#f1f6f2] p-3"><p className="text-xs font-semibold text-[#34483a]">{checkpoint.publicId}</p><p className="mt-1 text-xs text-[#6f8074]">{checkpoint.reason}</p><p className="mt-2 text-[10px] uppercase tracking-wide text-[#8a998f]">{checkpoint.status} · {formatDate(checkpoint.createdAt)}</p></div>)}</div><div className="mt-5"><h3 className="text-xs font-semibold uppercase tracking-[.12em] text-[#75867a]">Audited tool calls</h3><div className="mt-3 space-y-2">{data.audits.length === 0 ? <p className="text-xs text-[#819087]">No workspace request has been made.</p> : data.audits.map(audit => <div key={audit.publicId} className="flex items-center justify-between rounded-lg border border-[#e3ebe5] px-3 py-2"><span className="text-xs font-medium text-[#3b5141]">{audit.toolName}</span><span className="text-[10px] capitalize text-[#839188]">{audit.status}</span></div>)}</div></div></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-2"><Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Agent decision trail</h2><div className="mt-4 space-y-3">{data.decisions.length === 0 ? <p className="text-sm text-[#819087]">Structured rationales appear after agent runs.</p> : data.decisions.map(decision => <div key={decision.id} className="rounded-xl border border-[#e2ebe4] p-3"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-[#3b5141]">{decision.role}</p><span className="text-[10px] text-[#8b998f]">confidence {decision.confidence}%</span></div><p className="mt-2 text-xs leading-5 text-[#718076]">{decision.rationale}</p></div>)}</div></CardContent></Card><Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Token and cost ledger</h2><div className="mt-4 space-y-2">{data.costs.length === 0 ? <p className="text-sm text-[#819087]">Usage is recorded after the first model-backed agent run.</p> : data.costs.map(cost => <div key={cost.id} className="flex items-center justify-between rounded-xl border border-[#e2ebe4] px-3 py-2.5"><div><p className="text-xs font-semibold text-[#3b5141]">{cost.model}</p><p className="mt-1 text-[10px] text-[#89978e]">{cost.inputTokens.toLocaleString()} input · {cost.outputTokens.toLocaleString()} output tokens</p></div><span className="text-[10px] text-[#718076]">Tracked</span></div>)}</div></CardContent></Card></section>
    <section><Card className="border-[#dfe7e1]"><CardContent className="p-5"><h2 className="text-sm font-semibold text-[#26392d]">Project artifacts</h2><p className="mt-1 text-xs text-[#7d8c82]">Metadata for deliverables and generated files is kept in the project record; bytes belong in secure object storage.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.artifacts.length === 0 ? <p className="text-sm text-[#819087]">No artifact metadata has been registered yet.</p> : data.artifacts.map(artifact => <div key={artifact.publicId} className="rounded-xl border border-[#e2ebe4] p-3"><p className="truncate text-xs font-semibold text-[#3b5141]">{artifact.name}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-[#84938a]">{artifact.kind} · {artifact.sizeBytes.toLocaleString()} bytes</p><p className="mt-2 truncate text-[10px] text-[#718076]">{artifact.storageKey}</p></div>)}</div></CardContent></Card></section>
  </div>;
}
